### ISSUE TITLE
TYPO3 News: ":" is missing in News url

### ISSUE THREAD

**Issue by nitsan-technologies** [TYPO3-Initiatives/dashboard#113]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Can you reproduce the problem on TYPO3 v10
* [ ] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3-Initiatives%2FDashboard) to see if your bug or feature is already reported?

## Description

While opening News from TYPO3 News widget, News is not opening due to invalid News URL

## Steps to Reproduce

1. Go to Dashboard Module.
2. Click on "+" button and add TYPO3 News widget.
3. Once TYPO3 News widget is added successfully, Click on any News URL from widget.

**Expected behavior:** News link should open News successfully.

**Actual behavior:** Currently, News link is opening in new tab but ":" is missing after https. Because of this, News is not opening correctly.

Check this screen-cast:
![typo3-news](https://user-images.githubusercontent.com/2622317/73251854-bba6ba80-41df-11ea-88a9-4a2a847a6d1c.gif)

**Comment by haassie** [comment]
Thanks for finding this issue. This is due to spaces in the source of the RSS feed around the link. This will be fixed with the patch to core so we strip all spaces.
