### ISSUE TITLE
EDGE: Not able to move widgets once they have been added

### ISSUE THREAD

**Issue by nitsan-technologies** [TYPO3-Initiatives/dashboard#115]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Can you reproduce the problem on TYPO3 v10
* [ ] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3-Initiatives%2FDashboard) to see if your bug or feature is already reported?

## Description

Not possible to move widgets after they have been added. User need to re-add them in correct order

## Steps to Reproduce

1. Open Dashboard module in EDGE browser.
2. Click on "+" button and add multiple widgets.
3. Try to change positions of widgets.

**Expected behavior:** User should be able to change widgets' position.

**Actual behavior:** Currently, user is not able to change widget's position.

Check this screen-cast:-
![edge-widget-reposition](https://user-images.githubusercontent.com/2622317/73254292-21954100-41e4-11ea-959b-96e57e0add05.gif)

**Comment by haassie** [comment]
This problem is solved in the patch for core
