### ISSUE TITLE
EDGE: Resizing browser causes widgets to overlap each other

### ISSUE THREAD

**Issue by nitsan-technologies** [TYPO3-Initiatives/dashboard#117]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ ] Can you reproduce the problem on TYPO3 v10
* [ ] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3-Initiatives%2FDashboard) to see if your bug or feature is already reported?

## Description

When user resize EDGE browser, widgets overlaps each other.

## Steps to Reproduce

1. Open Dashboard module in EDGE Browser.
2. Add all the available widgets into Dashboard.
3. Resize the EDGE browser

**Expected behavior:** Widgets should be resized smoothly when browser is resized.

**Actual behavior:** widgets overlaps each other when browser is resized.

Check this screen-cast:-
![edge-resize-issue](https://user-images.githubusercontent.com/2622317/73264412-b73acb80-41f8-11ea-8415-74c94254cfa3.gif)

**Comment by haassie** [comment]
@KoenWouters can we reproduce this in the patch for core?

**Comment by KoenWouters** [comment]
@haassie This is fixed.
