### ISSUE TITLE
Add small description for all widgets in Add Widget box

### ISSUE THREAD

**Issue by nitsan-technologies** [TYPO3-Initiatives/dashboard#119]
# Feature Request

**Is your feature request related to a problem? Please describe.**
It would be helpful if there is a small description text for all widgets in Add Widget box. It may not be possible to understand the purpose of the widget by just name.

**Describe the solution you'd like**
We can add description text below Widget name in Add Widget box just the way we display in in Add Content element box

Something like this:

![widget_description](https://user-images.githubusercontent.com/2622317/73335595-e2272d00-4295-11ea-9d97-953ad13bf6cc.png)

**Comment by haassie** [comment]
This is already possible isn't it? See 
<img width="472" alt="Screenshot 2020-02-01 at 13 08 24" src="https://user-images.githubusercontent.com/11075733/73591836-fcf6dd00-44f3-11ea-959c-d6a07c943881.png">.
