### ISSUE TITLE
TYPO3 News: Link in widget to see all TYPO3 News

### ISSUE THREAD

**Issue by nitsan-technologies** [TYPO3-Initiatives/dashboard#120]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, only 5 latest TYPO3 News are being listed in TYPO3 News widget. In case if I want to view more than 5 News, I need to go to https://typo3.org/project/news to see all News

**Describe the solution you'd like**
I should be able to access All News page from widget. We can add a link in header of widget to access News Page: https://typo3.org/project/news

Something like this:

![all-news-link](https://user-images.githubusercontent.com/2622317/73336180-2666fd00-4297-11ea-96be-04869504cf2b.png)

**Comment by haassie** [comment]
Done in patch for master
