### ISSUE TITLE
Graphical design of module

### ISSUE THREAD

**Issue by haassie** [TYPO3-Initiatives/dashboard#14]
We need a graphical design of how the backend module should look like and also popups etc.

**Comment by haassie** [comment]
There were some designs made during T3UXW18. See attached screens:

<img width="1261" alt="Screenshot 2019-07-02 at 22 19 03" src="https://user-images.githubusercontent.com/11075733/60543762-6f61cd80-9d17-11e9-85e0-ee189f8ffb35.png">
<img width="1256" alt="Screenshot 2019-07-02 at 22 21 49" src="https://user-images.githubusercontent.com/11075733/60543899-cf587400-9d17-11e9-9ee7-7d7ed847c922.png">

We need to check if those designs are still ok, or that we can even make it a little bit better.

**Comment by haassie** [comment]
Be aware: this is no final design. Only mockups!

**Comment by haassie** [comment]
![Screenshot 2019-08-28 at 09 14 56](https://user-images.githubusercontent.com/11075733/63833931-6cc8d080-c974-11e9-9f79-732756bcdf4f.png)

Another option

**Comment by haassie** [comment]
@irenesacchi would be great if you can give your feedback on the current mock-ups of the dashboard

**Comment by irenesacchi** [comment]
I love the look of the TYPO3 website.

Using it in the dashboard is a very good idea and offer the recognition value with the TYPO3 community and organisation. 
I would love to use it as delivered default skin. 
I could also create an Icon library where the developer could pick what they need. 

In the best case there will be given the possibility to variate the primary color and base the other ones on a filtering variation. In this case it will be easy for the developer of a website to give a customer skin to his users without messing up too much with the look. The overall harmonic look would be maintained. And the user will win a customer look for their project.

**Comment by irenesacchi** [comment]
[TYPO3 design.pdf](https://github.com/TYPO3-Initiatives/dashboard/files/3569387/TYPO3.design.pdf)

**Comment by haassie** [comment]
Ok so we decide to go for this version:
![dashboard](https://user-images.githubusercontent.com/11075733/64649490-43e91680-d41d-11e9-8e6b-0ca9a8381024.png)
