### ISSUE TITLE
Widget: Overview of pages without description

### ISSUE THREAD

**Issue by haassie** [TYPO3-Initiatives/dashboard#18]
If EXT:seo is installed, we should provide a widget that is giving a list of pages that doesn't have a description filled in the page properties.

- Paginated (number of items per page should be configurable)
- Possibility to select starting point (so you can select part of the tree to get checked)

**Comment by gaumondp** [comment]
Maybe the fields to check should be flexible? Suppose you also wants to make sure meta keyword is always fill for your Solr search or any other field?

So if I got 3 different fields I want to check, I create 3 different instances of the dashboard item and set different values to each ones. The title of the widget and maybe a small description should be available to help editors understand what the widget is all about.
