### ISSUE TITLE
Widget: (TYPO3) News (RSS Reader)

### ISSUE THREAD

**Issue by ayacoo** [TYPO3-Initiatives/dashboard#33]
# Widget Request

You could provide administrators or integrators with information (news) from typo3.org.

**How can this widget help the user?**
It helps the user directly to obtain information about TYPO3 and especially with security messages to act quickly.

**Describe the information you would like to show**
Just simple like a rss feed. Title, Date, Link.

**Configuration options**
If we get different news categories, one could look for these filters. Example: I only want news from the security area.

Optional: You could also keep it more general and have any RSS feeds read out. Example: Tips for editors or custom RSS feeds.

**Additional context**
Comparable to: https://wordpress.org/plugins/admin-dashboard-rss-feed/

**Comment by haassie** [comment]
That's a very good idea. We will include it in our first release!

**Comment by haassie** [comment]
We have created a simple version of a RSS widget now. It is not configurable by a user, but it is by an integrator / developer. Later on we will add the option to configure widgets and than we may reconsider if it should be good to make it possible to set the URL of the RSS feed as a user. For now I will close this issue.
