### ISSUE TITLE
Anonymize IP address in 5 last logins

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Initiatives/dashboard#61]
the IP address must be anonymized using `\TYPO3\CMS\Core\Utility\IpAnonymizationUtility::anonymizeIp`

it could be discussed if this should only happen for non admins but I would do it for all - the log got it all

**Comment by haassie** [comment]
Do you think it is even necessary to show the IP-address at all?

**Comment by kevin-appelt** [comment]
For successful logins I would say „No need for the IP address“ but for failed logins it might be helpful - but in each and every case it should be anonymised!

**Comment by georgringer** [comment]
I would show it, maybe later it could be possible to configure the fields but that is a different topic
