### ISSUE TITLE
Button "Default" doesn't make sense

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Initiatives/dashboard#65]
After installing the extension, there is this large button "Default"
<img width="346" alt="Bildschirmfoto 2019-10-17 um 07 29 10" src="https://user-images.githubusercontent.com/1905663/67005111-d5e4de80-f0af-11e9-9fda-bfdf95445dd5.png">

I can't click on it, I don't know what to do, iMO it doesn't make sense. if it is for presentig the current layout, I would like to see that in the toolbar

**Comment by haassie** [comment]
This is because there is only 1 dashboard at the moment. This is the switch for multiple dashboards. Maybe we should hide this when only 1 dashboard is available?
