### ISSUE TITLE
Argument 1 passed to FriendsOfTYPO3\Dashboard\Registry\WidgetRegistry::getWidgetObject() must be of the type string, null given

### ISSUE THREAD

**Issue by fritzdacat** [TYPO3-Initiatives/dashboard#71]
# Bug Report

If I want to call the dashboard in the backend I get this error:

Oops, an error occurred!
Argument 1 passed to FriendsOfTYPO3\Dashboard\Registry\WidgetRegistry::getWidgetObject() must be of the type string, null given, called in /public/typo3conf/ext/dashboard/Classes/Controller/DashboardController.php on line 262

TYPO3 9.5.9
@Mittwald Managed Server
PHP 7.2-latest FPM

This error does not occur locally under MAMP with PHP 7.2.20

**Comment by sfsmfc** [comment]
@fritzdacat Can you please have a look, if you can clear the cache?

I can only see the same issue, if I switch from one dashboard version to another without clearing the cache (e.g. from version 1.0.0 to master).

**Comment by haassie** [comment]
The code of the controller is completely refactored. I will close this issue for now. If you have any problem with the latest version, please let us know.
